# Generated by Django 4.1.2 on 2023-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='default', max_length=100)),
                ('lastName', models.CharField(default='default', max_length=100)),
                ('phoneNumber', models.CharField(default='default', max_length=100)),
                ('email', models.CharField(default='default', max_length=100)),
                ('message', models.CharField(default='default', max_length=10000)),
            ],
        ),
    ]
