# Generated by Django 4.1.5 on 2023-02-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastName',
        ),
    ]
